apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesk-api
spec:
  selector:
    matchLabels:
      app: tesk-api
  replicas: 1
  template:
    metadata:
      labels:
        app: tesk-api
    spec:
      serviceAccountName: taskmaster
      containers:
      - name: tesk-api
        image: eu.gcr.io/tes-wes/tesk-api:v0.4.2
        env:
        - name: TESK_API_TASKMASTER_IMAGE_VERSION
          value: v0.6
        - name: TESK_API_TASKMASTER_FILER_IMAGE_VERSION
          value: v0.6
        - name: TESK_API_K8S_NAMESPACE
          value: default
        - name: TESK_API_TASKMASTER_SERVICE_ACCOUNT_NAME
          value: taskmaster
        - name: TESK_API_TASKMASTER_FTP_SECRET_NAME
          value: ftp-secret
        - name: TESK_API_AUTHORISATION_ENV_SUBGROUP
          value: EBI
        - name: SPRING_PROFILES_ACTIVE
          value: noauth

        - name: TESK_API_TASKMASTER_ENVIRONMENT_HOST_BASE_PATH
          value: '/tmp'

        - name: TESK_API_TASKMASTER_ENVIRONMENT_CONTAINER_BASE_PATH
          value: '/transfer'

        - name: TESK_API_TASKMASTER_ENVIRONMENT_TRANSFER_PVC_NAME
          value: 'transfer-pvc'

        - name: TESK_API_TASKMASTER_DEBUG
          value: "false"

        - name: TESK_API_SWAGGER_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-client-secret
              key: id
              optional: true
        ports:
        - containerPort: 8080